### ISSUE TITLE
Defective Dockerfile for SSFT22

### ISSUE THREAD

**Issue by recursion-ninja** [scallop-lang/scallop-lang.github.io#12] opened 2022-05-31 00:27 UTC
The [`Dockerfile`][0] for SSFT22, [which is actively linked to][1] on the [`lab0` webpage][2], does not successfully build.

The defect arises from a dissonance (likely a typo) between the filenames on lines [`6`][3] and [`50`][4]. Below I have, for convenience, clipped and aligned the two lines to elucidate the defect's root cause.

```
L06: … scallopy-0.1.1-cp39-cp39-manylinux_2_27_x86_64.whl …
                    ^
                    |
                    v
L56: … scallopy-0.1.0-cp39-cp39-manylinux_2_27_x86_64.whl …
```

To correct the build failure, and prevent a similar problem in the future, consider applying the following patch which utilizes the [`basename`][6] POSIX utility to infer the correct file name and treat the `$SCALLOPY_URL` value at the ["single source of truth."][5]

```
- python -m pip install ./scallopy-0.1.0-cp39-cp39-manylinux_2_27_x86_64.whl && \
+ python -m pip install `basename ${SCALLOPY_URL}` && \
```

[0]: https://github.com/scallop-lang/scallop-lang.github.io/blob/fbb7bf8a4d970f96e91d589d7aa7693f542f6355/ssft22/labs/Dockerfile
[1]: https://scallop-lang.github.io/ssft22/labs/Dockerfile
[2]: https://scallop-lang.github.io/ssft22/lab0.html
[3]: https://github.com/scallop-lang/scallop-lang.github.io/blob/fbb7bf8a4d970f96e91d589d7aa7693f542f6355/ssft22/labs/Dockerfile#L6
[4]: https://github.com/scallop-lang/scallop-lang.github.io/blob/fbb7bf8a4d970f96e91d589d7aa7693f542f6355/ssft22/labs/Dockerfile#L50
[5]: https://en.wikipedia.org/wiki/Single_source_of_truth
[6]: https://en.wikipedia.org/wiki/Basename

**Comment by moqingyan** [comment] 2022-05-31 01:46
Thank you for your feedback! The issue is fixed now. :)

**Closed as completed by moqingyan** 2022-05-31 01:46 UTC
